object Versions {
    // sorted by alphabet
    const val appcompat = "1.2.0"
    const val constraintlayout = "2.0.1"
    const val coordinatorlayout = "1.1.0"
    const val coroutines = "1.3.9"
    const val gradle = "4.0.1"
    const val hilt = "2.28.1-alpha"
    const val hiltAndroidX = "1.0.0-alpha02"
    const val junit = "4.13"
    const val kotlin = "1.4.10"
    const val kotlinter = "3.2.0"
    const val ktxActivity = "1.1.0"
    const val ktxCollection = "1.1.0"
    const val ktxCore = "1.3.2"
    const val ktxFragment = "1.2.5"
    const val legacySupportV4 = "1.0.0"
    const val lifecycle = "2.2.0"
    const val material = "1.2.1"
    const val multidex = "2.0.1"
    const val navigation = "2.3.0"
    const val recyclerview = "1.1.0"
    const val testJunit = "1.1.2"
    const val testEspresso = "3.3.0"
}