name: Cancel Previous Runs

on:
  pull_request:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.editorconfig'
      - 'docs/**'
      - 'preview/**'

jobs:
  cancel:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.5.0
        with:
          workflow_id: 2943946,2943947,2943948
          access_token: ${{ github.token }}