name: Android Unit Test CI

on:
  pull_request:
  push:
    branches:
      - '*'
    tags-ignore:
      - 'v*'
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - '.editorconfig'
      - 'docs/**'
      - 'preview/**'

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          architecture: x86
      - name: Unit Tests
        run: ./gradlew test